### PR TITLE
Remove `@eval` from everywhere

### LINKED ISSUE #45: Segmentation fault
@dpo, I had a weird segmentation fault (random occurrence), could you try to recreate?
````julia
using CUTEst
nlp = CUTEstModel("ROSENBR")
for i = 1:100000
    uhprod(nlp, false, [0.0;0.0], [0.0;0.0])
end
````

### PR DESCRIPTION
**Pull request by abelsiqueira**
Closes #45

### CODE REVIEW

File: src/CUTEst.jl [hunk 1]
```diff
@@ -13,7 +13,7 @@ cutest_instances = 0;
 
 type CUTEstModel
   meta    :: NLPModelMeta;
-  libname :: ASCIIString;
+  cutest_lib :: Any # Or Ptr{Void} ?
```
Comment (dpo) [inline src/CUTEst.jl]: Doesn't `dlopen` return a `Ptr{Void}`?

File: src/CUTEst.jl [hunk 2]
```diff
@@ -49,6 +49,21 @@ macro cutest_error()  # Handle nonzero exit codes.
   :(io_err[1] > 0 && throw(CUTEstException(io_err[1])))
 end
 
+macro dlsym(func, lib)
```
Comment (dpo) [inline src/CUTEst.jl]: Better indicate where you got this from, so we remember.

File: src/CUTEst.jl [hunk 3]
```diff
@@ -64,7 +79,8 @@ function sifdecoder(name :: ASCIIString)
   run(`$linker $sh_flags -o $libname.$soname ELFUN.o EXTER.o GROUP.o RANGE.o -L$cutest_dir/objects/$cutest_arch/double -lcutest_double`);
   run(`rm ELFUN.f EXTER.f GROUP.f RANGE.f ELFUN.o EXTER.o GROUP.o RANGE.o`);
   push!(Libdl.DL_LOAD_PATH,".")
-  return libname
+  cutest_lib = Libdl.dlopen(libname)
+  return cutest_lib
```
Comment (dpo) [inline src/CUTEst.jl]: I like it!

File: src/core_interface.jl [hunk 4]
```diff
@@ -8,11 +8,11 @@ export usetup, csetup, udimen, udimsh, udimse, uvartype, unames,
 
 function usetup(io_err::Array{Cint, 1}, input::Array{Cint, 1}, out::Array{Cint, 1},
     io_buffer::Array{Cint, 1}, n::Array{Cint, 1}, x::Array{Cdouble, 1},
-    x_l::Array{Cdouble, 1}, x_u::Array{Cdouble, 1}, libname)
-  @eval ccall(("cutest_usetup_", $(libname)), Void,
+    x_l::Array{Cdouble, 1}, x_u::Array{Cdouble, 1}, cutest_lib)
```
Comment (dpo) [inline src/core_interface.jl]: This seems a bit more tricky because users must now pass a pointer! I wonder if this is a recipe for hard crashes. Perhaps these functions should keep taking `libname` and call `dlopen` internally?!

File: src/julia_interface.jl [hunk 5]
```diff
@@ -22,13 +22,13 @@ function objcons(nlp :: CUTEstModel, x :: Array{Float64,1})
   f = Cdouble[0];
   c = Array(Float64, ncon);
   if ncon > 0
-    @eval ccall((:cutest_cfn_, $(nlp.libname)), Void,
+    ccall(@dlsym(:cutest_cfn_, nlp.cutest_lib), Void,
```
Comment (dpo) [inline src/julia_interface.jl]: Here it's ok because the pointer is part of the `nlp` object.

File: src/core_interface.jl (hunk 4 above)
Comment (abelsiqueira) [inline src/core_interface.jl]: Then maybe leave both, first because I like to use the core interface inside `CUTEst.jl` and the specialized interface, and because the time it takes is about 7 times longer with `dlopen`.

Comment (dpo) [inline src/core_interface.jl]: Oh I see. Ok, let's leave it then.

**Comment by abelsiqueira** [comment]
Updated regarding the comments

**Comment by dpo** [comment]
Thanks a lot for investigating this!!!
